"""change column type

Revision ID: 05a6cb49bf3f
Revises: 745e1352e97f
Create Date: 2018-05-09 15:27:58.217910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a6cb49bf3f'
down_revision = '745e1352e97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'car', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'car_booking', 'car', ['car_id'], ['id'])
    op.create_foreign_key(None, 'car_booking', 'user', ['renter_id'], ['id'])
    op.create_foreign_key(None, 'car_image', 'car', ['car_id'], ['id'])
    op.create_foreign_key(None, 'car_option', 'car', ['id'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'owner_review', 'user', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'renter_review', 'user', ['renter_id'], ['id'])
    op.create_foreign_key(None, 'user_bank', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_card', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_time', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'vacation_data', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacation_data', type_='foreignkey')
    op.drop_constraint(None, 'user_time', type_='foreignkey')
    op.drop_constraint(None, 'user_card', type_='foreignkey')
    op.drop_constraint(None, 'user_bank', type_='foreignkey')
    op.drop_constraint(None, 'renter_review', type_='foreignkey')
    op.drop_constraint(None, 'owner_review', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'car_option', type_='foreignkey')
    op.drop_constraint(None, 'car_image', type_='foreignkey')
    op.drop_constraint(None, 'car_booking', type_='foreignkey')
    op.drop_constraint(None, 'car_booking', type_='foreignkey')
    op.drop_constraint(None, 'car', type_='foreignkey')
    # ### end Alembic commands ###
