"""add owner send model

Revision ID: 0e6f2896ecfb
Revises: 83b146809b81
Create Date: 2018-05-06 19:35:39.543387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6f2896ecfb'
down_revision = '83b146809b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_send',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('booking_id', sa.String(), nullable=True),
    sa.Column('tran_amt', sa.Integer(), nullable=False),
    sa.Column('rsp_code', sa.String(length=128), nullable=False),
    sa.Column('bank_tran_id', sa.String(length=128), nullable=False),
    sa.Column('bank_rsp_code', sa.String(length=128), nullable=False),
    sa.Column('bank_rsp_message', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['car_booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_send_booking_id'), 'owner_send', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_owner_send_booking_id'), table_name='owner_send')
    op.drop_table('owner_send')
    # ### end Alembic commands ###
