"""add vacation data table

Revision ID: 169bf1dffc7c
Revises: 3a1769b8dd2f
Create Date: 2018-04-04 11:11:09.095765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169bf1dffc7c'
down_revision = '3a1769b8dd2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacation_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacation_data_user_id'), 'vacation_data', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacation_data_user_id'), table_name='vacation_data')
    op.drop_table('vacation_data')
    # ### end Alembic commands ###
