"""add message table

Revision ID: 303dfdf99fa1
Revises: 9bb5a36d0e30
Create Date: 2018-04-18 19:23:54.386380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303dfdf99fa1'
down_revision = '9bb5a36d0e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['car_booking.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_booking_id'), 'message', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_booking_id'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
