"""change model structure

Revision ID: 3db55a3c708c
Revises: ac5369d6c724
Create Date: 2018-04-10 19:35:33.899859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db55a3c708c'
down_revision = 'ac5369d6c724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_card', sa.Column('card_1', sa.String(length=128), nullable=False))
    op.add_column('user_card', sa.Column('card_2', sa.String(length=128), nullable=False))
    op.add_column('user_card', sa.Column('card_3', sa.String(length=128), nullable=False))
    op.add_column('user_card', sa.Column('card_4', sa.String(length=128), nullable=False))
    op.add_column('user_card', sa.Column('register_date', sa.DateTime(), nullable=True))
    op.drop_column('user_card', 'card_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_card', sa.Column('card_number', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('user_card', 'register_date')
    op.drop_column('user_card', 'card_4')
    op.drop_column('user_card', 'card_3')
    op.drop_column('user_card', 'card_2')
    op.drop_column('user_card', 'card_1')
    # ### end Alembic commands ###
