"""add filename column in Car Image

Revision ID: 540c302becc1
Revises: 0a769c5cda0a
Create Date: 2018-06-28 18:30:17.938294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540c302becc1'
down_revision = '0a769c5cda0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_image', sa.Column('filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_image', 'filename')
    # ### end Alembic commands ###
