"""user active in usercard

Revision ID: 6c44f8f5f859
Revises: 68d9b849361b
Create Date: 2018-04-12 15:40:59.909301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c44f8f5f859'
down_revision = '68d9b849361b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_card', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_card', 'active')
    # ### end Alembic commands ###
