"""change column type

Revision ID: 745e1352e97f
Revises: 0e1fc0521c97
Create Date: 2018-05-09 15:21:23.723232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745e1352e97f'
down_revision = '0e1fc0521c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_bank_user_id_fkey', 'user_bank', type_='foreignkey')

    op.alter_column('car', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80))
    op.alter_column('car', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('car_booking', 'car_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('car_booking', 'renter_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('car_image', 'car_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('car_option', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String())
    op.alter_column('message', 'receiver_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('message', 'sender_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('owner_review', 'owner_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('renter_review', 'renter_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80))
    op.alter_column('user_bank', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('user_card', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('user_time', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('vacation_data', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacation_data', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('user_time', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('user_card', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('user_bank_user_id_fkey', 'user_bank', 'user', ['user_id'], ['id'])
    op.alter_column('user_bank', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'id',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER())
    op.alter_column('renter_review', 'renter_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('owner_review', 'owner_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('message', 'sender_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('message', 'receiver_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('car_option', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER())
    op.alter_column('car_image', 'car_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('car_booking', 'renter_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('car_booking', 'car_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('car', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('car', 'id',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER())
    # ### end Alembic commands ###
