"""add image_index to carImage model

Revision ID: 7985ef2ab828
Revises: 303dfdf99fa1
Create Date: 2018-04-24 18:52:48.201808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7985ef2ab828'
down_revision = '303dfdf99fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_image', sa.Column('image_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_image', 'image_index')
    # ### end Alembic commands ###
