"""upgrade user card model

Revision ID: 7a4e99ff303f
Revises: 647c9beb17b5
Create Date: 2018-05-25 12:14:51.590972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4e99ff303f'
down_revision = '647c9beb17b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_card', sa.Column('customer_uid', sa.String(length=128), nullable=False))
    op.drop_column('user_card', 'cvc')
    op.drop_column('user_card', 'password')
    op.drop_column('user_card', 'expire_month')
    op.drop_column('user_card', 'card_4')
    op.drop_column('user_card', 'card_2')
    op.drop_column('user_card', 'card_3')
    op.drop_column('user_card', 'expire_year')
    op.drop_column('user_card', 'birth')
    op.drop_column('user_card', 'card_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_card', sa.Column('card_1', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('user_card', sa.Column('birth', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('user_card', sa.Column('expire_year', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('user_card', sa.Column('card_3', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('user_card', sa.Column('card_2', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('user_card', sa.Column('card_4', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('user_card', sa.Column('expire_month', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('user_card', sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('user_card', sa.Column('cvc', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.drop_column('user_card', 'customer_uid')
    # ### end Alembic commands ###
