"""add renter review table

Revision ID: 8256c3fca5c5
Revises: 73a7fd335be8
Create Date: 2018-05-08 17:53:19.735961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8256c3fca5c5'
down_revision = '73a7fd335be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('renter_review',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('booking_id', sa.String(), nullable=True),
    sa.Column('renter_id', sa.Integer(), nullable=True),
    sa.Column('review_point', sa.Float(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['car_booking.id'], ),
    sa.ForeignKeyConstraint(['renter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renter_review_booking_id'), 'renter_review', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_renter_review_booking_id'), table_name='renter_review')
    op.drop_table('renter_review')
    # ### end Alembic commands ###
