"""add bank model

Revision ID: 83b146809b81
Revises: 7985ef2ab828
Create Date: 2018-05-04 16:05:33.932203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b146809b81'
down_revision = '7985ef2ab828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bank',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_code_std', sa.String(length=128), nullable=True),
    sa.Column('bank_code_sub', sa.String(length=128), nullable=True),
    sa.Column('bank_name', sa.String(length=128), nullable=True),
    sa.Column('account_holder_info', sa.String(length=128), nullable=False),
    sa.Column('account_num', sa.String(length=128), nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('account_holder_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bank_user_id'), 'user_bank', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_bank_user_id'), table_name='user_bank')
    op.drop_table('user_bank')
    # ### end Alembic commands ###
