"""add booking image model

Revision ID: 9247b9acb4bd
Revises: 7a4e99ff303f
Create Date: 2018-05-28 18:08:48.285717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9247b9acb4bd'
down_revision = '7a4e99ff303f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_image',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('booking_id', sa.String(), nullable=True),
    sa.Column('sender_id', sa.String(), nullable=True),
    sa.Column('image', sa.Integer(), nullable=True),
    sa.Column('image_index', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['car_booking.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_image_booking_id'), 'booking_image', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_image_sender_id'), 'booking_image', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_image_sender_id'), table_name='booking_image')
    op.drop_index(op.f('ix_booking_image_booking_id'), table_name='booking_image')
    op.drop_table('booking_image')
    # ### end Alembic commands ###
