"""add Car Booking Table

Revision ID: 96cfe528a425
Revises: 169bf1dffc7c
Create Date: 2018-04-06 11:21:46.821807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96cfe528a425'
down_revision = '169bf1dffc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_booking',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('renter_id', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('insurance_price', sa.Integer(), nullable=True),
    sa.Column('owner_earning', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['renter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_booking_car_id'), 'car_booking', ['car_id'], unique=False)
    op.create_index(op.f('ix_car_booking_renter_id'), 'car_booking', ['renter_id'], unique=False)
    op.drop_index('ix_user_time_table_user_id', table_name='user_time_table')
    op.drop_table('user_time_table')
    op.drop_index('ix_vactaion_data_user_id', table_name='vactaion_data')
    op.drop_table('vactaion_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vactaion_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='vactaion_data_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vactaion_data_pkey')
    )
    op.create_index('ix_vactaion_data_user_id', 'vactaion_data', ['user_id'], unique=False)
    op.create_table('user_time_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dow', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('all_available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('end_time', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('register_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_time_table_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_time_table_pkey')
    )
    op.create_index('ix_user_time_table_user_id', 'user_time_table', ['user_id'], unique=False)
    op.drop_index(op.f('ix_car_booking_renter_id'), table_name='car_booking')
    op.drop_index(op.f('ix_car_booking_car_id'), table_name='car_booking')
    op.drop_table('car_booking')
    # ### end Alembic commands ###
