"""add payment table

Revision ID: 9bb5a36d0e30
Revises: fc16a44d76e6
Create Date: 2018-04-17 19:19:44.963283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb5a36d0e30'
down_revision = 'fc16a44d76e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('booking_id', sa.String(), nullable=True),
    sa.Column('mid', sa.String(), nullable=True),
    sa.Column('tid', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('is_cancel', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['car_booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_booking_id'), 'payment', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_booking_id'), table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
