"""add user_id column in OwnerSend table

Revision ID: a770e2c66212
Revises: 7c54572278ee
Create Date: 2018-05-18 11:28:11.170658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a770e2c66212'
down_revision = '7c54572278ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner_send', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_owner_send_user_id'), 'owner_send', ['user_id'], unique=False)
    op.create_foreign_key(None, 'owner_send', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owner_send', type_='foreignkey')
    op.drop_index(op.f('ix_owner_send_user_id'), table_name='owner_send')
    op.drop_column('owner_send', 'user_id')
    # ### end Alembic commands ###
