"""change card number

Revision ID: ac5369d6c724
Revises: 96cfe528a425
Create Date: 2018-04-10 16:26:44.412715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5369d6c724'
down_revision = '96cfe528a425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_card',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('expire_year', sa.String(length=2), nullable=False),
    sa.Column('expire_month', sa.String(length=2), nullable=False),
    sa.Column('cvc', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_card_user_id'), 'user_card', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_card_user_id'), table_name='user_card')
    op.drop_table('user_card')
    # ### end Alembic commands ###
