"""add description column to bookingimage table

Revision ID: ca25708ef348
Revises: 9247b9acb4bd
Create Date: 2018-05-28 18:55:17.790724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca25708ef348'
down_revision = '9247b9acb4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_image', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_image', 'description')
    # ### end Alembic commands ###
