"""add birth column in user card table

Revision ID: fc16a44d76e6
Revises: e41447e6741a
Create Date: 2018-04-16 17:46:46.125709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc16a44d76e6'
down_revision = 'e41447e6741a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_card', sa.Column('birth', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_card', 'birth')
    # ### end Alembic commands ###
