export const UPDATE_ADMIN_REDUCER="UPDATE_ADMIN_REDUCER";
export const UPDATE_UNPAID_LIST="UPDATE_UNPAID_LIST";
export const GET_PAYMENT_LIST="GET_PAYMENT_LIST";
export const CHANGE_CHECK="CHANGE_CHECK";
export const CHANGE_ALL_CHECK="CHANGE_ALL_CHECK";
export const FILTER_SENT_DATA="FILTER_SENT_DATA";
