# base image
FROM node:9.11.2-alpine
RUN mkdir -p /opt/app

ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

EXPOSE 3000


# you'll likely want the latest npm, reguardless of node version, for speed and fixes
RUN npm i npm@latest -g

WORKDIR /opt
COPY package.json package-lock.json* ./
RUN npm install && npm cache clean --force
ENV PATH /opt/node_modules/.bin:$PATH

# copy in our source code last, as it changes the most
WORKDIR /opt/app
COPY . /opt/app

# start app
CMD ["npm", "start"]
